from pystats_utils.pipeline.bivariant_table import BivariantTable
#from pystats_utils.pipeline.logistic_exploration import LogisticExploration
#from pystats_utils.pipeline.cox_exploration import CoxExploration